# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!([
  {name: "Adam Giegel", about: "I am a amatuer advertiser who is passionate about commercials", email: "adamgiegel@gmail.com", username: "agiegel16", password: "max"},
  {name: "Meghan Campbell", about: "I just love shooting movies!", email: "meghancampbell@gmail.com", username: "mcampbell16", password: "max"},
  {name: "Esther Kim", about: "I am a creative soul and enjoy promoting companies through photos", email: "adamgiegel@gmail.com", username: "ekim16", password: "max"},
  {name: "Gavin Moore", about: "I enjoy singing and making music.", email: "adamgiegel@gmail.com", username: "jcrescenzo", password: "jason"},
  {name: "Adam", about: "I'm 24 and have tons of great ideas to share.", email: "adamgiegel@gmail.com", username: "ccallahan", password: "connor"},
  {name: "Jason Crecsenzo", about: "I have so many ideas floating around in my head and dont know what to do with them.", email: "adamgiegel@gmail.com", username: "agiegel23", password: "max"},
  {name: "Connor Callahan", about: "Art is where its at.", email: "adamgiegel@gmail.com", username: "agiege2", password: "max"},
  {name: "Homer Simpson", about: "I have a job as a nuclear technician.  But my real passion is advertising.", email: "adamgiegel@gmail.com", username: "hsimpson", password: "bart"},
  {name: "Bruce Wayne", about: "Im a wealthy businessman and vigilante.  Whenever I catch a crook I always have a funny commercial idea.", email: "adamgiegel@gmail.com", username: "batman1", password: "robin"},
  {name: "Tony Stark", about: "Billionare playboy philanthropist who can design suits and take pics.", email: "adamgiegel@gmail.com", username: "ironman23", password: "pepper"},
  {name: "Clark Kent", about: "Journalist who is seeking to find my artsy side.", email: "adamgiegel@gmail.com", username: "superman4", password: "louis"},
  {name: "Bruce Banner", about: "I have been making short films for years and relish the chance to make an ad that is seen around the world.", email: "adamgiegel@gmail.com", username: "hulk", password: "punybanner"},
  {name: "Elon Musk", about: "Im a tech guy and am interested in making commercials for my company.", email: "adamgiegel@gmail.com", username: "tesla1", password: "tesla"},
  {name: "Neil Armstrong", about: "My song ideas are our of this world.", email: "adamgiegel@gmail.com", username: "narmstrong", password: "moon"},
  {name: "Micheal Phelps", about: "Ive been in commercials and always think I could do a better job.", email: "adamgiegel@gmail.com", username: "4timeOlympian", password: "gold"},
  {name: "Bart Simpson", about: "Skater dude who has a love of photography to showcase in an advertisement.", email: "adamgiegel@gmail.com", username: "cow", password: "stupidLisa"},
  {name: "Rocky Balboa", about: "Boxer who sees visions for commercials every time I get punched in the head...which happens a lot.", email: "adamgiegel@gmail.com", username: "italianStallion", password: "adrian"},
  {name: "Mister Tee", about: "I pity the fool who doesnt want to listen to my voice in ads.", email: "adamgiegel@gmail.com", username: "pity", password: "theFool"},
  {name: "Adrian Balboa", about: "I have learned how to be motivational and constantly have new ad ideas.", email: "adamgiegel@gmail.com", username: "Rocky", password: "rocky"},
  {name: "Jesse Ventura", about: "I was a Navy Seal and Wrestler...but shooting short videos is my real passion", email: "adamgiegel@gmail.com", username: "predator", password: "minnesota"},
  {name: "Arnold Schwarzenegger", about: "Ill be back to acting after I get this advertising bug off of me.", email: "adamgiegel@gmail.com", username: "terminator", password: "tuma"},
  ])

  Company.create!([
    {name: "Apple", about: "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook", contact: "Mary Jameson", username: "apple1", password: "computer"},
    {name: "Wendys", about: "Wendy's is an American international fast food restaurant chain founded by Dave Thomas on November 15, 1969, in Columbus, Ohio. The company moved its headquarters to Dublin, Ohio, on January 29, 2006. As of 2016, Wendy's was the world's third largest hamburger fast food chain with 6,500+ locations, following Burger King and McDonald's.", contact: "Jameson", username: "appl1", password: "computer"},
    {name: "Coke", about: "Coca-Cola, or Coke, is a carbonated soft drink[1] manufactured by The Coca-Cola Company. Originally intended as a patent medicine, it was invented in the late 19th century by John Stith Pemberton and was bought out by businessman Asa Griggs Candler, whose marketing tactics led Coca-Cola to its dominance of the world soft-drink market throughout the 20th century. The drink's name refers to two of its original ingredients: coca leaves, and kola nuts (a source of caffeine). The current formula of Coca-Cola remains a trade secret, although a variety of reported recipes and experimental recreations have been published.", contact: "Mary Jameson", username: "ale1", password: "computer"},
    {name: "McDonalds", about: "Back in 1954, a man named Ray Kroc discovered a small burger restaurant in California, and wrote the first page of our history. From humble beginnings as a small restaurant, we're proud to have become one of the world's leading food service brands with more than 36,000 restaurants in more than 100 countries", contact: "Mary Jameson", username: "pp1", password: "computer"},
    {name: "Budweiser", about: "The name Budweiser in America, advertised as the King of Beers, has been a mainstay in today's culture. Almost toted as a 'rock' in its industrial strength, but is it a stalworthy as claimed? It's always Lawyer Time in this little corner of beerland. Budweiser, the flagship beer of Anheuser-Busch and the best-selling brew in America, has been scrapping over the rights to its name for decades, and there's no sign of a letup anytime soon. The Budweiser saga began in 1876, when the E. Anheuser Brewing Association of St. Louis, Missouri, introduced Budweiser Lager Beer. Founded in 1860 by Eberhard Anheuser, the company was renamed the Anheuser-Busch Brewing Association in 1879, recognizing the contribution and leadership of then president Adolphus Busch.", contact: "Bud Weiser", username: "bud1", password: "beer"},
    {name: "Volkswagon", about: "Volkswagen, shortened to VW, is a German automaker founded on 28 May 1937 by the German Labour Front, and headquartered in Wolfsburg. It is the flagship marque of the Volkswagen Group, the largest automaker by worldwide sales in 2016 and 2017.", contact: "Jeremy Vroom", username: "car1", password: "auto"},
    {name: "Pepsi", about: "Pepsi is a carbonated soft drink manufactured by PepsiCo. Originally created and developed in 1893 by Caleb Bradham and introduced as Brad's Drink, it was renamed as Pepsi-Cola on August 28, 1898, and then as Pepsi in 1961", contact: "Diet Pepsi", username: "pop1", password: "pop"},
    {name: "Old Spice", about: "Old Spice is an American brand of male grooming products encompassing deodorants and antiperspirants, shampoos, body washes, and soaps. It is manufactured by Procter & Gamble.", contact: "Jebidiah Spice", username: "spice1", password: "deoderant"},
    {name: "Noxzema", about: "Cold cream is an emulsion of water and certain fats, usually including beeswax and various scent agents, designed to smooth skin and remove makeup. The emulsion is of a water in oil type unlike the oil in water type emulsion of vanishing cream, so-called because it seems to disappear when applied on skin. ", contact: "Jerome Faceclean", username: "facial", password: "cleaner"},
    {name: "FaceBook", about: "Facebook, Inc. is an American online social media and social networking service company. It is based in Menlo Park, California. Its was founded by Mark Zuckerberg, along with fellow Harvard College students and roommates Eduardo Saverin, Andrew McCollum, Dustin Moskovitz and Chris Hughes.", contact: "Mr. Book", username: "face1", password: "zuck"},
    {name: "ETrade", about: "E-Trade Financial Corporation is a financial services company organized in Delaware and headquartered in New York City. The company provides services for individuals and institutions that are investing online.", contact: "Money Bags", username: "money1", password: "dolla"},
    {name: "Doritos", about: "Doritos is an American brand of flavored tortilla chips produced since 1964 by Frito-Lay, a wholly owned subsidiary of PepsiCo. The original Doritos were not flavored. The first flavor was Taco, released in 1967, though other flavors have since debuted for the company. ", contact: "Jim Brown", username: "fiery1", password: "potatoe"},
    {name: "Nike", about: "Nike, Inc. is an American multinational corporation that is engaged in the design, development, manufacturing, and worldwide marketing and sales of footwear, apparel, equipment, accessories, and services. The company is headquartered near Beaverton, Oregon, in the Portland metropolitan area.", contact: "Micheal Jordan", username: "nike1", password: "jordans"},
    {name: "Pets.com", about: "Pets.com was a dot-com enterprise headquartered in San Francisco that sold pet supplies to retail customers. ", contact: "Jerry Swanson", username: "swanson1", password: "dog"},
    {name: "Chrysler", about: "Chrysler is one of the Big Three automobile manufacturers in the United States, headquartered in Auburn Hills, Michigan. The original Chrysler Corporation was founded by Walter Chrysler from the remains of the Maxwell Motor Company in 1925.", contact: "Jim Chrysler", username: "chrysler1", password: "car"},
    {name: "Monster.com", about: "Monster.com is a global employment website owned and operated by Monster Worldwide, Inc. It was created in 1999 through the merger of The Monster Board and Online Career Center. It is a subsidiary of Randstad Holding, a Dutch multinational human resource consulting firm, and is headquartered in Weston, Massachusetts.", contact: "Craig Smith", username: "monster1", password: "website"},
    {name: "Snickers", about: "Snickers is a brand name chocolate bar made by the American company Mars, Incorporated, consisting of nougat topped with caramel and peanuts that has been enrobed in milk chocolate. The annual global sales of Snickers was $2 billion as of 2004", contact: "Betty White", username: "candy1", password: "peanuts"},
    {name: "Twix", about: "Twix is a sweet made by Mars, Inc., consisting of a biscuit applied with other confectionery toppings and coatings. Twix are packaged with two or four bars in a wrapper. Miniature and other variations of Twix bars are also available.", contact: "Jason Hershey", username: "hershey1", password: "chocolate"},
    {name: "Kit Kat", about: "Kit Kat is a chocolate-covered wafer bar confection created by Rowntree's of York, United Kingdom, and is now produced globally by Nestlé, which acquired Rowntree in 1988, and closed it in 2006,[1] with the exception of the United States where it is made under license by H.B. Reese Candy Company, a division of The Hershey Company. The standard bars consist of two or four pieces composed of three layers of wafer, separated and covered by an outer layer of chocolate. Each finger can be snapped from the bar separately. There are many different flavours of Kit Kat, including milk, white, and dark chocolate.", contact: "Kit Cat", username: "crunch1", password: "cookie"},
    {name: "BMW", about: "BMW AG (German: [ˈbeːˈʔɛmˈveː]; originally an initialism for Bayerische Motoren Werke in German, or Bavarian Motor Works in English) is a German multinational company which currently produces automobiles and motorcycles, and also produced aircraft engines until 1945. The company was founded in 1916 and is headquartered in Munich, Bavaria. BMW produces motor vehicles in Germany, Brazil, China, India, South Africa, the United Kingdom, and the United States. In 2015, BMW was the world's twelfth largest producer of motor vehicles, with 2,279,503 vehicles produced.[2] The Quandt family are long-term shareholders of the company, with the remaining shares owned by public float.", contact: "Mario Andretti", username: "car2", password: "speedster"},
    {name: "Miller Lite", about: "Miller Lite, is a 4.2% ABV American light pale lager sold by MillerCoors of Milwaukee, Wisconsin, United States. Miller Lite competes with Anheuser-Busch's Bud Light beer. The company also produces Miller Genuine Draft and Miller High Life", contact: "Anheiser Busch", username: "beer4", password: "budsucks"},
    ])

    Idea.create!([
      {title: "You're not you when you're hungry", image: 'https://i.ytimg.com/vi/GkAnLtqWDhc/maxresdefault.jpg', video: "https://www.youtube.com/embed/bXL8QPWLbBo", song: "NA", description: "A group of guys play tackle football in the mud with Betty White in this Snickers ad that aired during Super Bowl XLIV. As she goes for a pass, one of the guys tackles her in a mud puddle. When she gets up, her teammate refers to her as Mike and asks what his deal is. They tell Mike that he is playing like Betty White and she retorts, That's not what your girlfriend says. A girl on the sidelines has had enough of their bickering and hands Mike a Snickers. She transforms into Mike and returns to the field where another player has turned into Abe Vigoda.", category: 'Candy', likes: 0, user_id: 1, offer_id: 1},
      {title: "Puppy Love", image: "https://www.gannett-cdn.com/-mm-/4fceda38b7bda5964b70a5d16ef93ad98865fc20/c=0-67-1280-786/local/-/media/USATODAY/WiresImages/2014/01/31/0b2ed9381a6157044a0f6a7067000fb8.jpg?width=3200&height=1680&fit=crop", video: "https://www.youtube.com/embed/7p_3lITiK_Q", song: "NA", description: "the sweet love story of an adorable golden retriever puppy and one of the beer brand’s iconic Clydesdale horses. Set to the dulcet tones of Passenger’s Let Her Go,", category: 'beverage', likes: 0, user_id: 2, offer_id: 2},
      {title: "Kids", image: 'https://upl.stack.com/wp-content/uploads/2018/11/01134230/Super-Bowl-Monster-Commercial-STACK-654x368.png', video: 'https://www.youtube.com/embed/myG8hq1Mk00', song: "NA", description: "Kids talk about what they want to be when they grow up.... if they are honest about what you are actually doing at that terrible job you have.", category: 'website', likes: 0, user_id: 3, offer_id: 1},
      {title: "Im Lovin It", image: "https://images.vice.com/noisey/content-images/article/pusha-t-wrote-mcdonalds-jingle-im-lovin-it/Screen-Shot-2016-06-02-at-3-09-54-PM.jpg?crop=1xw:0.8429441260744985xh;center,center&resize=1200:*", video: "NA", song: "<div id='rg_embed_link_422296' class='rg_embed_link' data-song-id='422296'>Read <a href='https://genius.com/Clipse-im-lovin-it-mcdonalds-commerical-lyrics'>“I'm Lovin' It (McDonald's Commerical)” by Clipse</a> on Genius</div> <script crossorigin src='//genius.com/songs/422296/embed.js'></script>", description: "We love some McCeeDees", category: 'food', likes: 0, user_id: 1, offer_id: 1},
      {title: "The Showdown", image: 'https://i.ytimg.com/vi/nvvkvZYl0ek/maxresdefault.jpg', video: 'https://www.youtube.com/embed/1shK-j_u6LI', song: "NA", description: "By playing off the famous rivalry between Michael Jordan and Larry Bird, “The Showdown” popularized the now-iconic basketball saying “nothing but net” in the middle of the biggest football game of the year. The catchphrase has become one of the most recognizable phrases in the sports world, permeating other pop culture arenas.", category: 'food', likes: 0, user_id: 4, offer_id: 1},
      {title: "Whassupp", image: 'https://media-assets-05.thedrum.com/cache/images/thedrum-prod/s3-news-tmp-108565-bud_wassup_2--default--1125.png', video: 'https://www.youtube.com/embed/bXL8QPWLbBo', song: "NA", description: "four male friends, speaking over the phone, greeted one another with the slang phrase ‘‘Whassup?!’’ ", category: 'food', likes: 0, user_id: 5, offer_id: 1},
      {title: "Hey Kid Its a Catch", image: 'https://cdn-images-1.medium.com/max/1181/1*Ko8EXeBE5lGU1nrJm5SMBg.jpeg', video: 'https://www.youtube.com/embed/xffOCZYX6F8', song: "NA", description: "Coke’s “Hey Kid, Catch” told a full, heartstrings-pulling story in 60 seconds while setting the standard for featuring sports celebrities in commercials.", category: "beverage", likes: 0, user_id: 1, offer_id: 1},
      {title: 'Imported From Detroit', image: 'https://i.ytimg.com/vi/SKL254Y_jtc/maxresdefault.jpg', video: 'https://www.youtube.com/embed/mYsFUFgOEmM', song: "NA", description: "It was a celebration of Detroit, American industry, and Chrysler’s comeback from bankruptcy.", category: 'vehicles', likes: 0, user_id: 1, offer_id: 1},
      {title: "Wheres the Beef", image: 'https://s.yimg.com/ny/api/res/1.2/_pruyW2686QLfOBl3wp9QQ--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9NzAwO2g9Mzkz/http://media.zenfs.com/en/homerun/feed_manager_auto_publish_494/6de7894a1fa0986db53414fc0702cdf6', video: 'https://www.youtube.com/embed/Ug75diEyiA0', song: "NA", description: "3 women are eating a cheeseburger from a competitor. The sandwich barely has any beef in comparison to Wendys burgers so the woman ask Wheres the beef.", category: 'food', likes: 0, user_id: 6, offer_id: 1},
      {title: "1984", image: 'https://upload.wikimedia.org/wikipedia/en/5/5d/Ad_apple_1984.jpg', video: 'https://www.youtube.com/embed/axSnW-ygU5g', song: "NA", description: "During a hot Cold War, Apple’s ad played on people’s fears by likening its rival, IBM, to an Orwellian Big Brother, set on dominating the personal computer industry. And featuring a female heroine", category: 'technology', likes: 0, user_id: 6, offer_id: 1},
      {title: "The Force", image: 'https://www.gannett-cdn.com/-mm-/9a10d18443197ab9a2a837953a60ea6375b5467c/c=4-0-1916-1080/local/-/media/2015/01/14/USATODAY/USATODAY/635568450361506748-vw-the-force-file-ad.jpg?width=3200&height=1680&fit=crop', video: 'https://www.youtube.com/embed/2zwMWLE9fBU', song: "NA", description: "“The Force” featured a kid ambling about his house dressed as Star Wars’ Darth Vader while attempting to use the Dark Side on everything from the family dog to the new Passat sitting in the driveway.", category: 'vehicles', likes: 0, user_id: 6, offer_id: 1},
      {title: "Respect", image: 'https://static.adweek.com/adweek.com-prod/wp-content/uploads/files/news_article/jeter-hed-2014.jpg', video: 'https://www.youtube.com/embed/LO6TpbqTTxI', song: "NA", description: "Respect. That’s what Derek Jeter of the New York Yankees is about. Everyone from Tiger Woods and Michael Jordan to Yankee haters tip their caps to Jeter in an epic 90-second commercial", category: 'clothes', likes: 0, user_id: 6, offer_id: 1},
      {title: "Cindy Crawford", image: 'http://www.media4.hw-static.com/media/2017/01/sbgc_clip_cindycrawford_cms-638x425.jpg', video: 'https://www.youtube.com/embed/pKN77NjWXxg', song: "NA", description: "Cindy Crawford drinks a pepsi.", category: 'beverages', likes: 0, user_id: 7, offer_id: 1},
      {title: "The Man Your Man Could Smell Like", image: 'http://1.bp.blogspot.com/_LKEgSIr4LiU/TD355vRH_LI/AAAAAAAAAsk/tPSH0uVSUAY/s400/Isaiah-Mustafa_400.jpg', video: 'https://www.youtube.com/embed/owGykVbfgUE', song: "NA", description: "The campaign centers on the eponymous Man Your Man Could Smell Like, played by actor Isaiah Mustafa Old Spice refers to him as Old Spice Man addressing the viewer in confident, rapid-fire monologues which promote the benefit of using Old Spice products. While reciting the monologues, Mustafa progresses through various activities, locations, costumes, and extraordinary situations, all in one uninterrupted take while maintaining constant eye-contact with the camera in a nonchalant demeanor", category: 'deodarant', likes: 0, user_id: 7, offer_id: 1},
      {title: "Farrah Fawcett and Joe Namath", image: 'https://i.ytimg.com/vi/7ClijtnPkfU/hqdefault.jpg', video: 'https://www.youtube.com/embed/7ClijtnPkfU', song: "NA", description: "football player Joe Namath and Charlie’s Angels star Farrah Fawcett lent their endorsement to Noxzema Shave Cream, with the catchline “Let Noxzema cream your face", category: 'body care', likes: 0, user_id: 7, offer_id: 1},
      {title: "Budweiser Frogs", image: 'https://malonemediagroup.com/wp-content/uploads/2013/11/Budweiser-Frogs-Commercial.png', video: 'https://www.youtube.com/embed/pVcbasIb8lQ', song: "NA", description: "3 Frogs on a pond are ribbeting but the way they ribbet says Bud Weis Er.  Insinuating that the frogs like Budweiser", category: 'beverage', likes: 0, user_id: 7, offer_id: 1},
      {title: "Britney Spears", image: 'http://townsquare.media/site/252/files/2011/09/Crap.jpg?w=980&q=75', video: 'https://www.youtube.com/embed/5fugLhNbwoY', song: "NA", description: "Britney Spears Music Video about Pepsi", category: 'beverage', likes: 0, user_id: 7, offer_id: 1},
      {title: "Like a Girl", image: '', video: 'https://www.youtube.com/embed/yIxA3o84syY', song: "NA", description: "Women make up the majority of consumers, commanding a whopping 70% to 80% of all consumer purchases. So why aren’t more advertisements made to resonate with them? That’s in part why Always 2015 ad for feminine care projects stole the show during a night dominated by displays of hyper-masculinity. By recasting the phrase “like a girl,” the spot made an emotional appeal for women to empower themselves, especially when it came to sports.", category: 'social issues', likes: 0, user_id: 7, offer_id: 1},
      {title: "Wasted", image: 'http://topbet.eu/news/wp-content/uploads/2014/01/etrade-monkey-hed-2013-640x360.jpg', video: 'https://www.youtube.com/embed/BnQMq5wtZcg', song: "NA", description: "A monkey dancing in an ETrade t shirt.  What can be funnier.", category: 'website', likes: 0, user_id: 8, offer_id: 1},
      {title: "Michael Jordan & Bugs Bunny", image: 'https://i.ytimg.com/vi/NrTHJeqZA2o/maxresdefault.jpg', video: 'https://www.youtube.com/embed/2URMB4NGbo8', song: "NA", description: "ad featuring the first buddying up of Air Jordan and Hare Jordan. The ad was visually significant for blending real-world footage with cartoon images, a style pioneered by films like 1988’s Who Framed Roger Rabbit? Meanwhile, it treaded new ground for the well-worn approach of pairing two American icons to drive sales—with the twist that, in this case, one of those icons was fictional.", category: 'clothing', likes: 0, user_id: 8, offer_id: 1},
      {title: "Halftime in America", image: 'https://i.ytimg.com/vi/RvhHp6IamuY/maxresdefault.jpg', video: 'https://www.youtube.com/embed/8iXdsvgpwc8', song: "NA", description: "the eternally rugged Clint Eastwood giving the auto industry — and America at large — a rousing halftime speech to rally and pull together. Few if any ads have been so pointed about the emotional state of the country at its time of airing, giving this spot an extra layer of historical significance.", category: 'vehicle', likes: 0, user_id: 9, offer_id: 1},
      {title: "Live the Flavor", image: 'https://i.ytimg.com/vi/kNxgxF-7SfA/hqdefault.jpg', video: 'https://www.youtube.com/embed/kNxgxF-7SfA', song: "NA", description: "a young man drives while eating a bag of Nacho Cheese Doritos. He gets preoccupied when he notices a girl eating the same Doritos on the sidewalk and suddenly crashes his car. His head slams into the steering wheel causing the chips to scatter but also grabs the girl’s attention. She runs over to help but slips and slams her head into his car door. Even after all of this, they stare lovingly into each other’s eyes. ", category: 'food', likes: 0, user_id: 10, offer_id: 1},
      {title: "Delivery Guy", image: 'https://static01.nyt.com/images/2010/07/19/business/media/19adco-inline/19adco-inline-popup.jpg', video: 'https://www.youtube.com/embed/Bo4GuDtI69A', song: "NA", description: "wherein rival delivery guys bond, then fight again, over a glass of Pepsi-Cola", category: 'beverages', likes: 0, user_id: 11, offer_id: 1},
      {title: "Wearable Napkins", image: 'https://www.businessinsider.in/thumb/msid-49995015,width-640,resizemode-4/Heres-what-the-logos-for-Amazon-Levis-and-HBO-Go-would-say-if-they-were-being-honest/Levis-Wearable-napkins-.jpg?899943', video: '', song: "NA", description: "Jeans are basically napkins because people rub their hands on them anyway.", category: 'clothing', likes: 0, user_id: 12, offer_id: 1},
      {title: "Just Do It", image: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201707/nike-647_071117061035.jpg', video: '', song: "NA", description: "Motivational poster to convince people to just do it and go after their dreams.", category: 'clothing', likes: 0, user_id: 12, offer_id: 1},
      {title: "Big Red", image: 'http://trickykegstands.com/media/bigRed.jpg', video: '', song: "https://www.youtube.com/embed/bCxiuuJVT-8", description: "In this jingle we talk about how great Big Red gum is.  You will be hooked.", category: 'candy', likes: 0, user_id: 12, offer_id: 1},
      {title: "Doublemint Gum", image: 'https://i.ytimg.com/vi/vXJFuThJaMQ/hqdefault.jpg', video: '', song: "https://www.youtube.com/embed/PkeVfJ9VYKg", description: "Twins are featured in this ad.  They live DoubleMint gum.", category: 'candy', likes: 0, user_id: 12, offer_id: 1},
      ])

Offer.create!([
  {amount: 2000, accepted: "No", rejected: "No", negotiate: "I want 2500", idea_id: 1, company_id: 1}
  ])
